# Generated by Django 5.2.3 on 2025-06-19 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amministratore',
            fields=[
                ('nome', models.CharField(max_length=100, null=True)),
                ('cognome', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('ente', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('Id_itinerario', models.CharField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=100, null=True)),
                ('descrizione', models.CharField(max_length=100, null=True)),
                ('durata', models.CharField(max_length=100, null=True)),
                ('maxpartecipanti', models.IntegerField()),
                ('tema', models.CharField(max_length=100, null=True)),
                ('stato', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tappa',
            fields=[
                ('ID_tappa', models.CharField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('descrizione', models.CharField(max_length=100, null=True)),
                ('luogo', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('nome', models.CharField(max_length=100, null=True)),
                ('cognome', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('nazionalita', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guida',
            fields=[
                ('nome', models.CharField(max_length=100, null=True)),
                ('cognome', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('abilitazione', models.CharField(max_length=100, null=True)),
                ('lingua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Itinerari.lingua')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Id_feedback', models.IntegerField(primary_key=True, serialize=False)),
                ('valutazione', models.IntegerField()),
                ('commento', models.CharField(max_length=100, null=True)),
                ('data', models.DateField(null=True)),
                ('turista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Itinerari.turista')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('Id_visita', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('oraInizio', models.DateField()),
                ('oraFine', models.DateField()),
                ('puntoIncontro', models.CharField(max_length=100, null=True)),
                ('stato', models.BooleanField()),
                ('numpersone', models.IntegerField()),
                ('descrizione', models.CharField(max_length=100, null=True)),
                ('guida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Itinerari.guida')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('Id_prenotazione', models.IntegerField(primary_key=True, serialize=False)),
                ('turista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Itinerari.turista')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Itinerari.visita')),
            ],
        ),
    ]
